{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "81df7a3f-018e-4fd0-b74c-581a9f4180e0",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "ccaee5b9826140a8a416f5c10348fe1f",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[1mBertModel LOAD REPORT\u001b[0m from: sentence-transformers/all-MiniLM-L6-v2\n",
      "Key                     | Status     |  | \n",
      "------------------------+------------+--+-\n",
      "embeddings.position_ids | UNEXPECTED |  | \n",
      "\n",
      "\u001b[3mNotes:\n",
      "- UNEXPECTED\u001b[3m\t:can be ignored when loading from different task/architecture; not ok if you expect identical arch.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ChromaDB collection: student_profiles\n",
      "Embedding model loaded: all-MiniLM-L6-v2\n",
      "PostgreSQL connected\n"
     ]
    }
   ],
   "source": [
    "from sentence_transformers import SentenceTransformer\n",
    "import chromadb\n",
    "import psycopg2\n",
    "import json\n",
    "import pandas as pd\n",
    "\n",
    "# ChromaDB\n",
    "# Creates or opens a persistent local Chroma fatabase folder\n",
    "    # Keeps the vector collections saved on disk instead of only in memory\n",
    "chroma_client = chromadb.PersistentClient(path='./chroma_db')\n",
    "# Collection that contains detailed profile text with resume information\n",
    "# Contains more information\n",
    "collection_rich = chroma_client.get_or_create_collection(\n",
    "    name='student_profiles_rich',\n",
    "    metadata={'hnsw:space': 'cosine'}\n",
    ")\n",
    "# Collection for shorter or more general profile summaries\n",
    "collection_broad = chroma_client.get_or_create_collection(\n",
    "    name='student_profiles_broad',\n",
    "    metadata={'hnsw:space': 'cosine'}\n",
    ")\n",
    "\n",
    "# Connect to Postgres\n",
    "# !!!Enter your own dbname, user, password, host, and port!!!\n",
    "# !!!Enter inside quotation marks ''\n",
    "conn = psycopg2.connect(\n",
    "    dbname='postgres',\n",
    "    user='postgres',\n",
    "    password='123456',\n",
    "    host='localhost',\n",
    "    port=5432\n",
    ")\n",
    "# Curser object used to execute SQL commands\n",
    "cur = conn.cursor()\n",
    "\n",
    "# Model\n",
    "model = SentenceTransformer('all-MiniLM-L6-v2')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "2c66c2b7-ed0a-4c68-974f-878a32b96b14",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Resumes loaded: 20\n",
      "Task1 profiles loaded: 20\n",
      "Task0 records loaded: 2000\n",
      "Task0 usable records: 2000\n",
      "\n",
      "Normalization ranges (combined task0 + task1):\n",
      "  academic:   5.873 – 10.000\n",
      "  skill:      5.100 – 30.929\n",
      "  experience: 0.000 – 6.667\n"
     ]
    }
   ],
   "source": [
    "# Load original resume files\n",
    "# !!!!!!! PASTE OWN FILE PATH FOR 'resumes_original.json'!!!!!!!\n",
    "with open('', 'r') as f:\n",
    "    resumes = json.load(f)['resumes']   # must extract nested 'resumes' key\n",
    "print(f'Resumes loaded: {len(resumes)}')\n",
    "\n",
    "# Load scored profiles for resumes from Task 1\n",
    "# !!!!!!! PASTE OWN FILE PATH FOR 'task1_final_output.json'!!!!!!!\n",
    "with open('', 'r') as f:\n",
    "    task1 = json.load(f)\n",
    "print(f'Task1 profiles loaded: {len(task1)}')\n",
    "\n",
    "# Load Task 0 output\n",
    "# !!!!!!! PASTE OWN FILE PATH FOR 'postgres_public_task0_final_output.json'!!!!!!!\n",
    "with open('', 'r') as f:\n",
    "    task0_all = json.load(f)\n",
    "print(f'Task0 records loaded: {len(task0)}')\n",
    "\n",
    "# Keep only Task 0 output\n",
    "major_lifts = {}\n",
    "for r in task0:\n",
    "    if r['major'] and r['major'] not in major_lifts:\n",
    "        major_lifts[r['major']] = {\n",
    "            'academic_lift':   r['academic_lift']   if r['academic_lift']   is not None else 0,\n",
    "            'skill_lift':      r['skill_lift']       if r['skill_lift']       is not None else 0,\n",
    "            'experience_lift': r['experience_lift']  if r['experience_lift']  is not None else 0\n",
    "        }\n",
    "\n",
    "# Map Task 1 major names to Task 0 major names\n",
    "task0 = [\n",
    "    r for r in task0_all\n",
    "    if r['major']\n",
    "    and r['academic_bucket']\n",
    "    and r['skill_bucket']\n",
    "    and r['experience_bucket']\n",
    "    and r['academic_score'] is not None\n",
    "    and r['skill_score'] is not None\n",
    "    and r['experience_score'] is not None\n",
    "]\n",
    "print(f'Task0 usable records: {len(task0)}')\n",
    "\n",
    "# Build lookup of lift values by Task 0 major\n",
    "MAJOR_MAP = {\n",
    "    'Computer Science':              'CSE',\n",
    "    'Computer Science: Game Design': 'CSE',\n",
    "    'Computer Engineering':          'CSE',\n",
    "    'Software Engineering':          'Software Engineer',\n",
    "    'Data Science':                  'IT',\n",
    "    'Information Systems':           'IT',\n",
    "    'Electrical Engineering':        'EEE',\n",
    "    'Mechanical Engineering':        'Mechanical',\n",
    "    'Economics':                     'Comm&Mgmt',\n",
    "    'Mathematics':                   'Sci&Tech',\n",
    "    'Statistics':                    'Sci&Tech',\n",
    "    'Design':                        'UI/UX',\n",
    "    'Cognitive Science (HCI)':       'UI/UX',\n",
    "    'Biomedical Engineering':        'ECE',\n",
    "}\n",
    "\n",
    "# Combine Task 1 scores with Mapped Task 0 lift values\n",
    "major_lifts = {}\n",
    "for r in task0:\n",
    "    if r['major'] not in major_lifts:\n",
    "        major_lifts[r['major']] = {\n",
    "            'academic_lift':   r['academic_lift']   if r['academic_lift']   is not None else 0,\n",
    "            'skill_lift':      r['skill_lift']       if r['skill_lift']       is not None else 0,\n",
    "            'experience_lift': r['experience_lift']  if r['experience_lift']  is not None else 0\n",
    "        }\n",
    "\n",
    "# Build lookup of lift values by Task 0 major\n",
    "task1_profiles = []\n",
    "for s in task1:\n",
    "    task0_major = MAJOR_MAP.get(s['major'], s['major'])\n",
    "    lifts = major_lifts.get(task0_major, {\n",
    "        'academic_lift': 0, 'skill_lift': 0, 'experience_lift': 0\n",
    "    })\n",
    "    # Combine Task 1 scores with mapped Task 0 lift values\n",
    "    task1_profiles.append({\n",
    "        'student_key':       s['student_key'],\n",
    "        'cgpa':              s['cgpa'],\n",
    "        'major':             s['major'],\n",
    "        'task0_major':       task0_major,\n",
    "        'academic_score':    s['academic_score'],\n",
    "        'skill_score':       s['skill_score'],\n",
    "        'experience_score':  s['experience_score'],\n",
    "        'academic_lift':     lifts['academic_lift'],\n",
    "        'skill_lift':        lifts['skill_lift'],\n",
    "        'experience_lift':   lifts['experience_lift'],\n",
    "    })\n",
    "\n",
    "# Collect all scores from Task 0 and Task 1 for shared normalization\n",
    "all_acad  = [r['academic_score']   for r in task0] + [p['academic_score']   for p in task1_profiles]\n",
    "all_skill = [r['skill_score']      for r in task0] + [p['skill_score']      for p in task1_profiles]\n",
    "all_exp   = [r['experience_score'] for r in task0] + [p['experience_score'] for p in task1_profiles]\n",
    "\n",
    "# Store min/max ranges for later normalization\n",
    "NORM = {\n",
    "    'acad_min':  min(all_acad),   'acad_max':  max(all_acad),\n",
    "    'skill_min': min(all_skill),  'skill_max': max(all_skill),\n",
    "    'exp_min':   min(all_exp),    'exp_max':   max(all_exp),\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "id": "a255b589-6349-4a1f-a70d-e69e2b2c1a07",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Building collection_rich (20 resume-text vectors)...\n",
      "collection_rich loaded: 20 documents\n",
      "\n",
      "Building collection_broad (2,000 score-profile vectors)...\n",
      "  Embedded 200/2000\n",
      "  Embedded 400/2000\n",
      "  Embedded 600/2000\n",
      "  Embedded 800/2000\n",
      "  Embedded 1000/2000\n",
      "  Embedded 1200/2000\n",
      "  Embedded 1400/2000\n",
      "  Embedded 1600/2000\n",
      "  Embedded 1800/2000\n",
      "  Embedded 2000/2000\n",
      "collection_broad loaded: 2000 documents\n",
      "\n",
      "Populating PostgreSQL task3_students...\n",
      "PostgreSQL task3_students populated\n"
     ]
    }
   ],
   "source": [
    "# # Convert one resume dict into a single text string for embedding\n",
    "def resume_to_text(resume: dict) -> str:\n",
    "    major      = resume.get('college', {}).get('major', '')\n",
    "    cgpa       = resume.get('academics', {}).get('cgpa', '')\n",
    "    courses    = ', '.join([\n",
    "        c.get('course', '')\n",
    "        for c in resume.get('academics', {}).get('relevant_coursework', [])\n",
    "    ])\n",
    "    awards     = ', '.join([\n",
    "        a.get('title', '')\n",
    "        for a in resume.get('academics', {}).get('honors_or_awards', [])\n",
    "    ])\n",
    "    tech       = ', '.join(resume.get('skills', {}).get('technical', []))\n",
    "    soft       = ', '.join(resume.get('skills', {}).get('soft', []))\n",
    "    projects   = ', '.join([\n",
    "        p.get('name', '')\n",
    "        for p in resume.get('experience', {}).get('projects', [])\n",
    "    ])\n",
    "    work       = ', '.join([\n",
    "        w.get('title', '')\n",
    "        for w in resume.get('experience', {}).get('work', [])\n",
    "    ])\n",
    "    activities = ', '.join([\n",
    "        a.get('activity', '')\n",
    "        for a in resume.get('experience', {}).get('leadership_and_activities', [])\n",
    "    ])\n",
    "    return (\n",
    "        f'Major: {major}. CGPA: {cgpa}. '\n",
    "        f'Courses: {courses}. Awards: {awards}. '\n",
    "        f'Technical skills: {tech}. Soft skills: {soft}. '\n",
    "        f'Projects: {projects}. Work: {work}. Activities: {activities}.'\n",
    "    )\n",
    "\n",
    "# # Scale a score to the 0–1 range\n",
    "def normalize_score(value: float, min_val: float, max_val: float) -> float:\n",
    "    if max_val == min_val:\n",
    "        return 0.0\n",
    "    return round((value - min_val) / (max_val - min_val), 6)\n",
    "\n",
    "# Convert structured profile scores into text for embedding\n",
    "def profile_to_text(major: str, academic_score: float,\n",
    "                    skill_score: float, experience_score: float,\n",
    "                    academic_bucket: str, skill_bucket: str,\n",
    "                    experience_bucket: str) -> str:\n",
    "    acad_n  = normalize_score(academic_score,   NORM['acad_min'],  NORM['acad_max'])\n",
    "    skill_n = normalize_score(skill_score,       NORM['skill_min'], NORM['skill_max'])\n",
    "    exp_n   = normalize_score(experience_score,  NORM['exp_min'],   NORM['exp_max'])\n",
    "    return (\n",
    "        f'Major: {major}. '\n",
    "        f'Academic score: {acad_n:.3f} ({academic_bucket}). '\n",
    "        f'Skill score: {skill_n:.3f} ({skill_bucket}). '\n",
    "        f'Experience score: {exp_n:.3f} ({experience_bucket}).'\n",
    "    )\n",
    "\n",
    "# Compute placement prediction from normalized scores and lift weights\n",
    "# Returns placement_prediction as a percentage (0–100).\n",
    "def compute_placement_prediction(academic_score, skill_score, experience_score,\n",
    "                                  academic_lift, skill_lift, experience_lift) -> float:\n",
    "    # Normalize scores to 0–1\n",
    "    acad_n  = normalize_score(academic_score,   NORM['acad_min'],  NORM['acad_max'])\n",
    "    skill_n = normalize_score(skill_score,       NORM['skill_min'], NORM['skill_max'])\n",
    "    exp_n   = normalize_score(experience_score,  NORM['exp_min'],   NORM['exp_max'])\n",
    "\n",
    "    # Clamp negative lifts to 0\n",
    "    al = max(academic_lift,   0)\n",
    "    sl = max(skill_lift,      0)\n",
    "    el = max(experience_lift, 0)\n",
    "    total_lift = al + sl + el\n",
    "\n",
    "    # Use equal-weight average if all lifts are 0\n",
    "    if total_lift == 0:\n",
    "        return round(((acad_n + skill_n + exp_n) / 3.0) * 100, 1)\n",
    "\n",
    "    # Compute lift-weighted percentage\n",
    "    raw = (acad_n * al) + (skill_n * sl) + (exp_n * el)\n",
    "    return round((raw / total_lift) * 100, 1)\n",
    "\n",
    "# Build rich-text vector collection from 20 resumes\n",
    "print('Building collection_rich (20 resume-text vectors)...')\n",
    "texts_rich      = [resume_to_text(r) for r in resumes]\n",
    "ids_rich        = [r['student_key'] for r in resumes]\n",
    "embeddings_rich = model.encode(texts_rich).tolist()\n",
    "metadatas_rich  = [\n",
    "    {\n",
    "        'student_key': r['student_key'],\n",
    "        'major':       r['college']['major'],\n",
    "        'cgpa':        str(r['academics']['cgpa']),\n",
    "        'source':      'task1_resume'\n",
    "    }\n",
    "    for r in resumes\n",
    "]\n",
    "\n",
    "# Store rich resume embeddings in ChromaDB\n",
    "collection_rich.add(\n",
    "    ids=ids_rich,\n",
    "    embeddings=embeddings_rich,\n",
    "    metadatas=metadatas_rich,\n",
    "    documents=texts_rich\n",
    ")\n",
    "\n",
    "print(f'collection_rich loaded: {collection_rich.count()} documents')\n",
    "\n",
    "# Build broad vector collection from Task 0 score profiles\n",
    "print('\\nBuilding collection_broad (2,000 score-profile vectors)...')\n",
    "\n",
    "texts_broad, ids_broad, embeddings_broad, metadatas_broad = [], [], [], []\n",
    "\n",
    "BATCH_SIZE = 200\n",
    "for i, r in enumerate(task0):\n",
    "    # Convert each Task 0 record into normalized profile text\n",
    "    text = profile_to_text(\n",
    "        r['major'],\n",
    "        r['academic_score'],\n",
    "        r['skill_score'],\n",
    "        r['experience_score'],\n",
    "        r['academic_bucket'],\n",
    "        r['skill_bucket'],\n",
    "        r['experience_bucket']\n",
    "    )\n",
    "    # Compute structured placement prediction\n",
    "    pp = compute_placement_prediction(\n",
    "        r['academic_score'],   r['skill_score'],   r['experience_score'],\n",
    "        r['academic_lift'] or 0, r['skill_lift'] or 0, r['experience_lift'] or 0\n",
    "    )\n",
    "    texts_broad.append(text)\n",
    "    ids_broad.append(r['student_key'])\n",
    "    metadatas_broad.append({\n",
    "        'student_key':          r['student_key'],\n",
    "        'major':                r['major'],\n",
    "        'placed':               str(r['placed']),\n",
    "        'academic_bucket':      r['academic_bucket'],\n",
    "        'skill_bucket':         r['skill_bucket'],\n",
    "        'experience_bucket':    r['experience_bucket'],\n",
    "        'placement_prediction': str(pp),\n",
    "        'source':               'task0_profile'\n",
    "    })\n",
    "\n",
    "# Add broad profiles to ChromaDB in batches\n",
    "for start in range(0, len(texts_broad), BATCH_SIZE):\n",
    "    batch_texts = texts_broad[start:start + BATCH_SIZE]\n",
    "    batch_embs  = model.encode(batch_texts).tolist()\n",
    "    collection_broad.add(\n",
    "        ids=ids_broad[start:start + BATCH_SIZE],\n",
    "        embeddings=batch_embs,\n",
    "        metadatas=metadatas_broad[start:start + BATCH_SIZE],\n",
    "        documents=batch_texts\n",
    "    )\n",
    "    print(f'  Embedded {min(start + BATCH_SIZE, len(texts_broad))}/{len(texts_broad)}')\n",
    "\n",
    "print(f'collection_broad loaded: {collection_broad.count()} documents')\n",
    "\n",
    "\n",
    "# Populate PostgreSQL table with all Task 1 and Task 0 students\n",
    "print('\\nPopulating PostgreSQL task3_students...')\n",
    "\n",
    "# Insert task1 students\n",
    "for profile in task1_profiles:\n",
    "    pp = compute_placement_prediction(\n",
    "        profile['academic_score'],   profile['skill_score'],   profile['experience_score'],\n",
    "        profile['academic_lift'],    profile['skill_lift'],    profile['experience_lift']\n",
    "    )\n",
    "    cur.execute('''\n",
    "        INSERT INTO proj.task3_students\n",
    "        (student_key, cgpa, major, academic_score, skill_score,\n",
    "         experience_score, academic_lift, skill_lift, experience_lift,\n",
    "         placement_prediction)\n",
    "        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)\n",
    "        ON CONFLICT (student_key) DO UPDATE SET\n",
    "            placement_prediction = EXCLUDED.placement_prediction\n",
    "    ''', (\n",
    "        profile['student_key'], profile['cgpa'],\n",
    "        profile['major'],       profile['academic_score'],\n",
    "        profile['skill_score'], profile['experience_score'],\n",
    "        profile['academic_lift'], profile['skill_lift'],\n",
    "        profile['experience_lift'], pp\n",
    "    ))\n",
    "\n",
    "# Insert task0 students\n",
    "for r in task0:\n",
    "    pp = compute_placement_prediction(\n",
    "        r['academic_score'],      r['skill_score'],      r['experience_score'],\n",
    "        r['academic_lift'] or 0,  r['skill_lift'] or 0,  r['experience_lift'] or 0\n",
    "    )\n",
    "    cur.execute('''\n",
    "        INSERT INTO proj.task3_students\n",
    "        (student_key, cgpa, major, academic_score, skill_score,\n",
    "         experience_score, academic_lift, skill_lift, experience_lift,\n",
    "         placement_prediction)\n",
    "        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)\n",
    "        ON CONFLICT (student_key) DO UPDATE SET\n",
    "            placement_prediction = EXCLUDED.placement_prediction\n",
    "    ''', (\n",
    "        r['student_key'], None,\n",
    "        r['major'],       r['academic_score'],\n",
    "        r['skill_score'], r['experience_score'],\n",
    "        r['academic_lift'] or 0, r['skill_lift'] or 0,\n",
    "        r['experience_lift'] or 0, pp\n",
    "    ))\n",
    "\n",
    "# Save all inserts to PostgreSQL\n",
    "conn.commit()\n",
    "print('PostgreSQL task3_students populated')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "id": "e5154832-1f8a-4a23-9a38-4a689a63f2e0",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Find the most similar resumes from the 20 rich-text profiles\n",
    "def find_rich_similar(query_resume: dict, k: int = 5) -> list:\n",
    "    query_text = resume_to_text(query_resume)\n",
    "    query_emb  = model.encode([query_text]).tolist()\n",
    "    student_key = query_resume['student_key']\n",
    "\n",
    "    # Query ChromaDB and exclude the same student\n",
    "    results = collection_rich.query(\n",
    "        query_embeddings=query_emb,\n",
    "        n_results=k + 1,                          # fetch one extra to account for self\n",
    "        where={'student_key': {'$ne': student_key}},  # exclude self\n",
    "        include=['distances', 'metadatas']\n",
    "    )\n",
    "    \n",
    "    # Return top k matches with key metadata\n",
    "    return [\n",
    "        {\n",
    "            'student_key': results['ids'][0][i],\n",
    "            'distance':    round(results['distances'][0][i], 4),\n",
    "            'major':       results['metadatas'][0][i]['major'],\n",
    "            'cgpa':        results['metadatas'][0][i]['cgpa'],\n",
    "            'collection':  'rich (resume text)',\n",
    "        }\n",
    "        for i in range(min(k, len(results['ids'][0])))  # cap at k\n",
    "    ]\n",
    "\n",
    "# Find the most similar Task 0 profiles from the broad collection\n",
    "def find_broad_similar(academic_score: float, skill_score: float,\n",
    "                        experience_score: float,\n",
    "                        academic_bucket: str, skill_bucket: str,\n",
    "                        experience_bucket: str, major: str,\n",
    "                        k: int = 5, filter_major: bool = True) -> list:\n",
    "    # Build query text using the same format as stored profiles\n",
    "    query_text = profile_to_text(\n",
    "        MAJOR_MAP.get(major, major),\n",
    "        academic_score, skill_score, experience_score,\n",
    "        academic_bucket, skill_bucket, experience_bucket\n",
    "    )\n",
    "    query_emb = model.encode([query_text]).tolist()\n",
    "\n",
    "    # Optionally restrict search to the same mapped major\n",
    "    where = {'major': MAJOR_MAP.get(major, major)} if filter_major else None\n",
    "\n",
    "    # Query ChromaDB for nearest score-profile matches\n",
    "    results = collection_broad.query(\n",
    "        query_embeddings=query_emb,\n",
    "        n_results=k,\n",
    "        where=where,\n",
    "        include=['distances', 'metadatas']\n",
    "    )\n",
    "    \n",
    "    # Return matches with profile metadata\n",
    "    return [\n",
    "        {\n",
    "            'student_key':       results['ids'][0][i],\n",
    "            'distance':          round(results['distances'][0][i], 4),\n",
    "            'major':             results['metadatas'][0][i]['major'],\n",
    "            'placed':            results['metadatas'][0][i]['placed'],\n",
    "            'academic_bucket':   results['metadatas'][0][i]['academic_bucket'],\n",
    "            'skill_bucket':      results['metadatas'][0][i]['skill_bucket'],\n",
    "            'experience_bucket': results['metadatas'][0][i]['experience_bucket'],\n",
    "            'placement_prediction': results['metadatas'][0][i]['placement_prediction'],\n",
    "            'collection':        'broad (score profile)',\n",
    "        }\n",
    "        for i in range(len(results['ids'][0]))\n",
    "    ]\n",
    "\n",
    "# Find students with higher placement prediction than the query student\n",
    "def find_stronger_peers(query_pp: float, query_major: str = None,\n",
    "                         limit: int = 3) -> list:\n",
    "    if query_major:\n",
    "        task0_major = MAJOR_MAP.get(query_major, query_major)\n",
    "        # Search only within the same mapped major\n",
    "        cur.execute('''\n",
    "            SELECT student_key, cgpa, major, academic_score,\n",
    "                   skill_score, experience_score, placement_prediction\n",
    "            FROM proj.task3_students\n",
    "            WHERE placement_prediction > %s\n",
    "              AND major = %s\n",
    "            ORDER BY placement_prediction DESC\n",
    "            LIMIT %s\n",
    "        ''', (query_pp, task0_major, limit))\n",
    "    else:\n",
    "        # Search across all students\n",
    "        cur.execute('''\n",
    "            SELECT student_key, cgpa, major, academic_score,\n",
    "                   skill_score, experience_score, placement_prediction\n",
    "            FROM proj.task3_students\n",
    "            WHERE placement_prediction > %s\n",
    "            ORDER BY placement_prediction DESC\n",
    "            LIMIT %s\n",
    "        ''', (query_pp, limit))\n",
    "    rows = cur.fetchall()\n",
    "    cols = ['student_key', 'cgpa', 'major', 'academic_score',\n",
    "            'skill_score', 'experience_score', 'placement_prediction']\n",
    "    \n",
    "    # Convert SQL rows into dictionaries\n",
    "    return [dict(zip(cols, row)) for row in rows]\n",
    "\n",
    "# Compute percentile rank based on placement prediction\n",
    "def compute_placement_percentile(query_pp: float) -> dict:\n",
    "    # Count total students and how many are below the query score\n",
    "    cur.execute('''\n",
    "        SELECT\n",
    "            COUNT(*) AS total,\n",
    "            SUM(CASE WHEN placement_prediction < %s THEN 1 ELSE 0 END) AS below\n",
    "        FROM proj.task3_students\n",
    "    ''', (query_pp,))\n",
    "    row = cur.fetchone()\n",
    "    total, below = row[0], row[1]\n",
    "    percentile = round((below / total) * 100, 1) if total > 0 else 0\n",
    "    return {'percentile': percentile, 'below': below, 'total': total}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "4fe13bd1-1378-4bae-a935-96c8a0444e97",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Run the full Task 3 comparison workflow for one student\n",
    "def run_task3(query_resume: dict, query_profile: dict):\n",
    "    sk    = query_profile['student_key']\n",
    "    major = query_profile['major']\n",
    "    cgpa  = query_profile['cgpa']\n",
    "\n",
    "    # Get Task 1 bucket labels for the query student\n",
    "    t1_record    = next((s for s in task1 if s['student_key'] == sk), None)\n",
    "    acad_bucket  = t1_record['academic_bucket']   if t1_record else 'Medium'\n",
    "    skill_bucket = t1_record['skill_bucket']      if t1_record else 'Medium'\n",
    "    exp_bucket   = t1_record['experience_bucket'] if t1_record else 'Medium'\n",
    "\n",
    "    # Compute the student's placement prediction\n",
    "    query_pp = compute_placement_prediction(\n",
    "        query_profile['academic_score'],   query_profile['skill_score'],\n",
    "        query_profile['experience_score'], query_profile['academic_lift'],\n",
    "        query_profile['skill_lift'],       query_profile['experience_lift']\n",
    "    )\n",
    "\n",
    "    # Print the query student's summary\n",
    "    print(f'Student Key — {sk} | {major} | CGPA: {cgpa}')\n",
    "    print(f'Scores: acad={query_profile[\"academic_score\"]}  '\n",
    "          f'skill={query_profile[\"skill_score\"]}  '\n",
    "          f'exp={query_profile[\"experience_score\"]}')\n",
    "    print(f'Buckets: {acad_bucket} / {skill_bucket} / {exp_bucket}')\n",
    "    print(f'placement_prediction: {query_pp}%')\n",
    "\n",
    "    # Output 1 - ChromaDB\n",
    "    # Find top 5 similar students from the rich resume-text collection\n",
    "    rich_results = find_rich_similar(query_resume, k=5)\n",
    "    rich_keys    = tuple(r['student_key'] for r in rich_results)\n",
    "    # Fetch structured scores for those matched students\n",
    "    cur.execute('''\n",
    "        SELECT student_key, academic_score, skill_score,\n",
    "               experience_score, placement_prediction\n",
    "        FROM proj.task3_students WHERE student_key IN %s\n",
    "    ''', (rich_keys,))\n",
    "    rich_scores = {row[0]: row[1:] for row in cur.fetchall()}\n",
    "\n",
    "    # Build Output 1 table\n",
    "    df1 = pd.DataFrame(rich_results)\n",
    "    df1['academic_score']       = df1['student_key'].map(lambda k: rich_scores.get(k, (None,)*4)[0])\n",
    "    df1['skill_score']          = df1['student_key'].map(lambda k: rich_scores.get(k, (None,)*4)[1])\n",
    "    df1['experience_score']     = df1['student_key'].map(lambda k: rich_scores.get(k, (None,)*4)[2])\n",
    "    df1['placement_prediction'] = df1['student_key'].map(\n",
    "        lambda k: f'{rich_scores.get(k, (None,)*4)[3]}%'\n",
    "        if rich_scores.get(k, (None,)*4)[3] is not None else 'N/A'\n",
    "    )\n",
    "    df1 = df1.sort_values('distance').reset_index(drop=True)\n",
    "\n",
    "    # Print output\n",
    "    print('\\nOUTPUT 1 — Top 5 Similar Resume Peers (collection_rich)')\n",
    "    print('Question: \"Which of the 20 detailed resume peers is most similar to me?\"')\n",
    "    print('Method:   Full resume text embedding (semantic similarity)')\n",
    "    print(df1[['student_key', 'distance', 'major', 'cgpa',\n",
    "               'academic_score', 'skill_score',\n",
    "               'experience_score', 'placement_prediction']].to_string(index=False))\n",
    "\n",
    "    # Output 2\n",
    "    # Find stronger peers from PostgreSQL\n",
    "    stronger   = find_stronger_peers(query_pp, query_major=major, limit=3)\n",
    "    percentile = compute_placement_percentile(query_pp)\n",
    "\n",
    "    # Print\n",
    "    print(f'\\nOUTPUT 2 — Top 3 Stronger Comparison Students (PostgreSQL)')\n",
    "    print(f'Question: \"Who has better placement odds than me in '\n",
    "          f'{MAJOR_MAP.get(major, major)}?\"')\n",
    "    print(f'NOTE: Queried across ALL 2,020 students — not filtered from Output 1.')\n",
    "    print(f'Your placement percentile: top '\n",
    "          f'{100 - percentile[\"percentile\"]:.1f}% '\n",
    "          f'(outperform {percentile[\"below\"]} of {percentile[\"total\"]} students)')\n",
    "\n",
    "    # Build stronger-peer comparison table\n",
    "    if stronger:\n",
    "        df2 = pd.DataFrame(stronger)\n",
    "        df2['placement_prediction'] = df2['placement_prediction'].apply(\n",
    "            lambda x: f'{float(x):.1f}%' if x is not None else 'N/A'\n",
    "        )\n",
    "        print(df2[['student_key', 'major', 'academic_score',\n",
    "                   'skill_score', 'experience_score',\n",
    "                   'placement_prediction']].to_string(index=False))\n",
    "\n",
    "        # Compare the query student to the top stronger peer\n",
    "        top = stronger[0]\n",
    "        print('\\nIMPROVEMENT DIRECTION (vs top stronger peer):')\n",
    "        for col, label in [\n",
    "            ('academic_score',   'Academic Score '),\n",
    "            ('skill_score',      'Skill Score    '),\n",
    "            ('experience_score', 'Experience Score')\n",
    "        ]:\n",
    "            mine   = query_profile.get(col, 0)\n",
    "            theirs = float(top[col])\n",
    "            # Normalize scores before comparing gaps\n",
    "            if col == 'academic_score':\n",
    "                mine_n   = normalize_score(mine,   NORM['acad_min'],  NORM['acad_max'])\n",
    "                theirs_n = normalize_score(theirs, NORM['acad_min'],  NORM['acad_max'])\n",
    "            elif col == 'skill_score':\n",
    "                mine_n   = normalize_score(mine,   NORM['skill_min'], NORM['skill_max'])\n",
    "                theirs_n = normalize_score(theirs, NORM['skill_min'], NORM['skill_max'])\n",
    "            else:\n",
    "                mine_n   = normalize_score(mine,   NORM['exp_min'],   NORM['exp_max'])\n",
    "                theirs_n = normalize_score(theirs, NORM['exp_min'],   NORM['exp_max'])\n",
    "            # Print normalized score gap\n",
    "            diff  = round((theirs_n - mine_n) * 100, 1)\n",
    "            arrow = '▲' if diff > 0 else '✓'\n",
    "            print(f'  {arrow}  {label}: you={mine_n*100:.1f}%  |  '\n",
    "                  f'peer={theirs_n*100:.1f}%  |  gap={diff:+.1f}%')\n",
    "    else:\n",
    "        # Case where no stronger peer exists\n",
    "        print('You already outperform all students in this major by placement_prediction!')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "id": "b69d262b-176e-44ae-9049-e897aee1a005",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Student Key — u_0007 | Computer Science | CGPA: 3.62\n",
      "Scores: acad=7.38  skill=5.1  exp=3.23\n",
      "Buckets: High / Low / Low\n",
      "placement_prediction: 28.9%\n",
      "\n",
      "OUTPUT 1 — Top 5 Similar Resume Peers (collection_rich)\n",
      "Question: \"Which of the 20 detailed resume peers is most similar to me?\"\n",
      "Method:   Full resume text embedding (semantic similarity)\n",
      "student_key  distance            major cgpa academic_score skill_score experience_score placement_prediction\n",
      "     u_0020    0.0469 Computer Science 3.95         7.8800      6.1500           3.2300             30.6000%\n",
      "     u_0004    0.0542     Data Science 3.88         7.7700      5.1000           3.0500             35.3000%\n",
      "     u_0016    0.0628     Data Science 3.33         6.9500      5.1000           3.2300             30.8000%\n",
      "     u_0001    0.0711 Computer Science 3.41         7.0700      5.1000           3.2300             28.9000%\n",
      "     u_0013    0.0786 Computer Science 3.47         7.1600      5.1000           3.2300             28.9000%\n",
      "\n",
      "OUTPUT 2 — Top 3 Stronger Comparison Students (PostgreSQL)\n",
      "Question: \"Who has better placement odds than me in CSE?\"\n",
      "NOTE: Queried across ALL 2,020 students — not filtered from Output 1.\n",
      "Your placement percentile: top 93.7% (outperform 127 of 2020 students)\n",
      "student_key major academic_score skill_score experience_score placement_prediction\n",
      "     d3_469   CSE         8.3600     25.2503           5.3333                79.2%\n",
      "     d3_295   CSE         8.6850     25.7148           4.6667                74.0%\n",
      "    d3_1493   CSE         7.8853     23.8216           5.0000                74.0%\n",
      "\n",
      "IMPROVEMENT DIRECTION (vs top stronger peer):\n",
      "  ▲  Academic Score : you=36.5%  |  peer=60.3%  |  gap=+23.7%\n",
      "  ▲  Skill Score    : you=0.0%  |  peer=78.0%  |  gap=+78.0%\n",
      "  ▲  Experience Score: you=48.4%  |  peer=80.0%  |  gap=+31.5%\n"
     ]
    }
   ],
   "source": [
    "# Demonstration\n",
    "# student_key = u_0007\n",
    "query_resume_7  = next(r for r in resumes if r['student_key'] == 'u_0007')\n",
    "query_profile_7 = next(p for p in task1_profiles if p['student_key'] == 'u_0007')\n",
    "run_task3(query_resume_7, query_profile_7)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "ddbb51d5-0486-4401-b11a-bfa9b26899ee",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Student Key — u_0020 | Computer Science | CGPA: 3.95\n",
      "Scores: acad=7.88  skill=6.15  exp=3.23\n",
      "Buckets: High / High / High\n",
      "placement_prediction: 30.6%\n",
      "\n",
      "OUTPUT 1 — Top 5 Similar Resume Peers (collection_rich)\n",
      "Question: \"Which of the 20 detailed resume peers is most similar to me?\"\n",
      "Method:   Full resume text embedding (semantic similarity)\n",
      "student_key  distance            major cgpa academic_score skill_score experience_score placement_prediction\n",
      "     u_0007    0.0469 Computer Science 3.62         7.3800      5.1000           3.2300             28.9000%\n",
      "     u_0013    0.0713 Computer Science 3.47         7.1600      5.1000           3.2300             28.9000%\n",
      "     u_0001    0.0716 Computer Science 3.41         7.0700      5.1000           3.2300             28.9000%\n",
      "     u_0017    0.0833 Computer Science 2.94         6.3600      5.1000           3.2300             28.9000%\n",
      "     u_0004    0.0847     Data Science 3.88         7.7700      5.1000           3.0500             35.3000%\n",
      "\n",
      "OUTPUT 2 — Top 3 Stronger Comparison Students (PostgreSQL)\n",
      "Question: \"Who has better placement odds than me in CSE?\"\n",
      "NOTE: Queried across ALL 2,020 students — not filtered from Output 1.\n",
      "Your placement percentile: top 90.4% (outperform 193 of 2020 students)\n",
      "student_key major academic_score skill_score experience_score placement_prediction\n",
      "     d3_469   CSE         8.3600     25.2503           5.3333                79.2%\n",
      "     d3_295   CSE         8.6850     25.7148           4.6667                74.0%\n",
      "    d3_1493   CSE         7.8853     23.8216           5.0000                74.0%\n",
      "\n",
      "IMPROVEMENT DIRECTION (vs top stronger peer):\n",
      "  ▲  Academic Score : you=48.6%  |  peer=60.3%  |  gap=+11.6%\n",
      "  ▲  Skill Score    : you=4.1%  |  peer=78.0%  |  gap=+73.9%\n",
      "  ▲  Experience Score: you=48.4%  |  peer=80.0%  |  gap=+31.5%\n"
     ]
    }
   ],
   "source": [
    "# Demonstration\n",
    "# student_key = u_0020\n",
    "query_resume_20  = next(r for r in resumes if r['student_key'] == 'u_0020')\n",
    "query_profile_20 = next(p for p in task1_profiles if p['student_key'] == 'u_0020')\n",
    "run_task3(query_resume_20, query_profile_20)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
